version: '3.8'
services:

  db-service:
    image: postgres:15
    environment:
      POSTGRES_DB: PRUEBA
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Script SQL inicial

volumes:
  postgres_data:
